### ISSUE TITLE
AddTaskCustom必须自己实现CustomHandler吗

### ISSUE THREAD

**Issue by LiuYuLu** [2881099/FreeScheduler#14]
<img width="619" alt="image" src="https://user-images.githubusercontent.com/16041268/195038459-822be7df-8e7e-4010-9a42-6ce1d472ba1e.png">

NextDelay的具体实现可以给个demo吗？
另外，实现的MyCustomTaskHandler，可以同时实现 ITaskIntervalCustomHandler、FreeSqlHandler吗？分开实现有什么优势吗？

**Comment by 2881099** [comment]
可以同时实现，分开也可以，反正内部只认接口。

CronHelper 参考：https://www.cnblogs.com/berkerdong/p/16619415.html

var nextTime = CronHelper.GetNextOccurrence(task.IntervalArgument);
return nextTime - DateTimeOffset.UtcNow;

**Comment by LiuYuLu** [comment]
感谢解答
