### ISSUE TITLE
临时任务不能取消

### ISSUE THREAD

**Issue by chunjieyaya** [2881099/FreeScheduler#22]
![image](https://github.com/2881099/FreeScheduler/assets/43339684/e9cce751-a0ea-4ee7-9373-3fd5ed45d41c)
这个任务用  Scheduler.RemoveTempTask 取消不了

**Comment by 2881099** [comment]
1秒太短了，可能取消不了

**Comment by chunjieyaya** [comment]
> 1秒太短了，可能取消不了

临时任务，想取消的时候，里面的方法也不让执行，有办法吗？

**Comment by chunjieyaya** [comment]
明白了，好的。
