### ISSUE TITLE
建议不要默认依赖FreeSqL

### ISSUE THREAD

**Issue by coolqingcheng** [2881099/FreeScheduler#3]
如果现有项目没使用freesql，引入这个库，会默认把FreeSql包也加进去

**Comment by 2881099** [comment]
自带一个持久化实现，所以依赖 FreeSql.dll

FreeSql.dll 是绿色零依赖包，没会给你的项目带来冲突

**Comment by coolqingcheng** [comment]
好的，谢谢

**Comment by jianxuanbing** [comment]
> 自带一个持久化实现，所以依赖 FreeSql.dll
> 
> FreeSql.dll 是绿色零依赖包，不会给你的项目带来冲突

我觉得可以抽象存储

**Comment by 2881099** [comment]
引用没关系，可以不使用的啊。

FreeScheduler.TaskHandlers.FreeRedis 这个抽出来了。
