### ISSUE TITLE
MyTaskHandler如何使用依赖注入？现在例子是直接new

### ISSUE THREAD

**Issue by coolqingcheng** [2881099/FreeScheduler#4]

**Comment by 2881099** [comment]
ITaskHandler 没必要注入，注入也是单例

service.AddSingletion(scheduler);

**Comment by coolqingcheng** [comment]
意思是我在MyTaskHandler里面调用了我的一个其他现有的类。但是这个类构造函数注入了其他的东西，如果我去new的话。，这些构造参数都需要弄进去。
按照现在的使用逻辑，MyTaskHandler 只能尽量不依赖其他的类。
或者说我使用ServiceProvider创建一个scope，从scope里面获取依赖注入的对象，这样MyTaskHandler就只需要传递一个ServiceProvider

**Comment by coolqingcheng** [comment]
意思是我在MyTaskHandler里面调用了我的一个其他现有的类。但是这个类构造函数注入了其他的东西，如果我去new的话。，这些构造参数都需要弄进去。
按照现在的使用逻辑，MyTaskHandler 只能尽量不依赖其他的类。
或者说我使用ServiceProvider创建一个scope，从scope里面获取依赖注入的对象，这样MyTaskHandler就只需要传递一个ServiceProvider

**Comment by 2881099** [comment]
那就注入吧

service.AddSingletion\<ITaskHandler\>(...);
service.AddSingletion\<Scheduler\>();

**Comment by coolqingcheng** [comment]
这样多个定时任务就不好搞了。。

**Comment by 2881099** [comment]
是这样设计的，多个任务都在一个 ITaskHandler 内触发，用 Topic 判断任务。
