### ISSUE TITLE
Feature Request AHeadTask Api Need

### ISSUE THREAD

**Issue by sgf** [2881099/FreeScheduler#6]
添加 scheduler.AHeadTask Api
就是让一个Task下次触发任务提前执行。然后其他不变。

如果可以，给这个API加个bool 参数。是否修改计时器(true/false).
是-立即执行后，变成等10分钟。
否-相当于，当前插入一个执行。下次执行还是等5分钟。

例如：
Task 每次10分钟执行一次。
当前时间距离下次执行还有5分钟。
现在要对其进行干预，跳过这5分钟，立即执行任务。
执行后下次执行就还是等10分钟。

**Comment by sgf** [comment]
如果可以，给这个API加个参数。是否修改计时器(true/false).
是-立即执行后，变成等10分钟。
否-相当于，当前插入一个执行。下次执行还是等5分钟。

**Comment by 2881099** [comment]
## v1.0.8 

- 增加 RunNowTask(taskid) 方法立刻运行任务；#6
- 增加 ScanInterval 属性设置更高精度的定时需求；
